version: 2

sources:
  - name: compras_gov
    schema: compras_gov
    tables:
      - name: contratos
      - name: faturas
      - name: empenhos
      - name: cronograma
      - name: terceirizados
  
  - name: siafi
    schema: siafi
    tables:
      - name: empenhos_tesouro
      - name: estagios_tesouro
      - name: nc_tesouro
      - name: pf_tesouro
      - name: visao_orcamentaria_total
  
  - name: transfere_gov
    schema: transfere_gov
    tables:
      - name: notas_de_credito
      - name: planos_acao
      - name: programacao_financeira
      - name: programas
  - name: siape 
    schema: siape 
    tables:
      - name: lista_uorgs 
      - name: lista_servidores
      - name: dados_uorg
      - name: dados_pessoais
      - name: dados_pa
      - name: dados_funcionais
      - name: dados_financeiros
      - name: dados_escolares
      - name: dados_dependentes
      - name: dados_curriculo
      - name: dados_afastamento
      - name: afastamento_historico

  - name: siorg
    schema: siorg
    tables:
      - name: estrutura_organizacional_cargos
      - name: cargos_funcao
      - name: unidade_organizacional

  - name: transferegov_emendas
    schema: transferegov_emendas
    tables:
      - name: programas_especiais
      - name: planos_acao_especiais
      - name: empenhos_especiais
      - name: ordens_bancarias_especiais
      - name: historico_pagamentos_especiais
      - name: plano_trabalho_especial
      - name: documentos_habeis_especiais
      - name: relatorio_gestao_especial
      - name: relatorios_gestao_novo_especial
      - name: executor_especial
      - name: metas_especiais
      - name: finalidades_especiais

  - name: dados_abertos
    schema: camara_deputados
    tables: 
      - name: deputados

  - name: senado_federal
    schema: senado_federal
    tables:
      - name: senadores

  - name: ipea_pro
    schema: ipea_pro
    tables:
      - name: bolsistas
      - name: coordenacoes
      - name: custosemprojetos
      - name: diretorias
      - name: fontesreceitas
      - name: grupoentidade
      - name: insumofinanceiro
      - name: itemfontereceitas
      - name: itenscustos
      - name: projetos
      - name: registrofinanceiroemprojetos
      - name: servidorespublicos
      - name: statusprojetos

  - name: sisbolsas
    schema: sisbolsas
    tables:
      - name: tb_area_formacao
      - name: tb_bolsa
      - name: tb_bolsa_coordenador
      - name: tb_bolsa_fonterecurso
      - name: tb_bolsista
      - name: tb_chamada_publica
      - name: tb_chapubli_fontfina
      - name: tb_chapubli_unidade
      - name: tb_coordenador
      - name: tb_dado_formacao
      - name: tb_dado_pessoal
      - name: tb_dado_profissional
      - name: tb_estado
      - name: tb_folha_bolsista
      - name: tb_folha_pagamento
      - name: tb_fonte_financeira
      - name: tb_modalidade
      - name: tb_nivel_escolaridade
      - name: tb_processo_seletivo
      - name: tb_programa
      - name: tb_selecao
      - name: tb_situacao_chamada
      - name: tb_situacao_concessao
      - name: tb_unidade
      - name: tb_usuario
