TABELAS_SICONV = [
    {
        "nome_tabela": "proposta",
        "nome_csv": "siconv_proposta.csv",
        "conflict_fields": ["id_proposta"],
        "primary_key": ["id_proposta"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA", "UF_PROPONENTE", "MUNIC_PROPONENTE", "COD_MUNIC_IBGE",
            "COD_ORGAO_SUP", "DESC_ORGAO_SUP", "NATUREZA_JURIDICA", "NR_PROPOSTA",
            "DIA_PROP", "MES_PROP", "ANO_PROP", "DIA_PROPOSTA", "COD_ORGAO",
            "DESC_ORGAO", "MODALIDADE", "IDENTIF_PROPONENTE", "NM_PROPONENTE",
            "CEP_PROPONENTE", "ENDERECO_PROPONENTE", "BAIRRO_PROPONENTE", "NM_BANCO",
            "SITUACAO_CONTA", "SITUACAO_PROJETO_BASICO", "SIT_PROPOSTA",
            "DIA_INIC_VIGENCIA_PROPOSTA", "DIA_FIM_VIGENCIA_PROPOSTA",
            "OBJETO_PROPOSTA", "ITEM_INVESTIMENTO", "ENVIADA_MANDATARIA",
            "NOME_SUBTIPO_PROPOSTA", "DESCRICAO_SUBTIPO_PROPOSTA", "VL_GLOBAL_PROP",
            "VL_REPASSE_PROP", "VL_CONTRAPARTIDA_PROP", "CD_AGENCIA", "CD_CONTA",
        ],
    },
    {
        "nome_tabela": "convenio",
        "nome_csv": "siconv_convenio.csv",
        "conflict_fields": ["nr_convenio"],
        "primary_key": ["nr_convenio"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "ID_PROPOSTA", "DIA", "MES", "ANO", "DIA_ASSIN_CONV",
            "SIT_CONVENIO", "SUBSITUACAO_CONV", "SITUACAO_PUBLICACAO", "INSTRUMENTO_ATIVO",
            "IND_OPERA_OBTV", "NR_PROCESSO", "UG_EMITENTE", "DIA_PUBL_CONV",
            "DIA_INIC_VIGENC_CONV", "DIA_FIM_VIGENC_CONV", "DIA_FIM_VIGENC_ORIGINAL_CONV",
            "DIAS_PREST_CONTAS", "DIA_LIMITE_PREST_CONTAS", "DATA_SUSPENSIVA",
            "DATA_RETIRADA_SUSPENSIVA", "DIAS_CLAUSULA_SUSPENSIVA", "SITUACAO_CONTRATACAO",
            "IND_ASSINADO", "MOTIVO_SUSPENSAO", "IND_FOTO", "QTDE_CONVENIOS", "QTD_TA",
            "QTD_PRORROGA", "VL_GLOBAL_CONV", "VL_REPASSE_CONV", "VL_CONTRAPARTIDA_CONV",
            "VL_EMPENHADO_CONV", "VL_DESEMBOLSADO_CONV", "VL_SALDO_REMAN_TESOURO",
            "VL_SALDO_REMAN_CONVENENTE", "VL_RENDIMENTO_APLICACAO", "VL_INGRESSO_CONTRAPARTIDA",
            "VL_SALDO_CONTA", "VALOR_GLOBAL_ORIGINAL_CONV",
        ],
    },
    {
        "nome_tabela": "desembolso",
        "nome_csv": "siconv_desembolso.csv",
        "conflict_fields": ["id_desembolso"],
        "primary_key": ["id_desembolso"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_DESEMBOLSO", "NR_CONVENIO", "DT_ULT_DESEMBOLSO", "QTD_DIAS_SEM_DESEMBOLSO",
            "DATA_DESEMBOLSO", "ANO_DESEMBOLSO", "MES_DESEMBOLSO", "NR_SIAFI",
            "UG_EMITENTE_DH", "OBSERVACAO_DH", "VL_DESEMBOLSADO",
        ],
    },
    {
        "nome_tabela": "desbloqueio",
        "nome_csv": "siconv_desbloqueio_cr.csv",
        "conflict_fields": [],
        "primary_key": [],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "NR_OB", "DATA_CADASTRO", "DATA_ENVIO",
            "TIPO_RECURSO_DESBLOQUEIO", "VL_TOTAL_DESBLOQUEIO",
            "VL_DESBLOQUEADO", "VL_BLOQUEADO",
        ],
    },
    {
        "nome_tabela": "solicitacao_alteracao",
        "nome_csv": "siconv_solicitacao_alteracao.csv",
        "conflict_fields": ["id_solicitacao"],
        "primary_key": ["id_solicitacao"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_SOLICITACAO", "NR_CONVENIO", "NR_SOLICITACAO", "SITUACAO_SOLICITACAO",
            "OBJETO_SOLICITACAO", "DATA_SOLICITACAO",
        ],
    },
    {
        "nome_tabela": "termo_aditivo",
        "nome_csv": "siconv_termo_aditivo.csv",
        "conflict_fields": ["nr_convenio", "numero_ta"],
        "primary_key": ["nr_convenio", "numero_ta"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "ID_SOLICITACAO", "NUMERO_TA", "TIPO_TA",
            "VL_GLOBAL_TA", "VL_REPASSE_TA", "VL_CONTRAPARTIDA_TA",
            "DT_ASSINATURA_TA", "DT_INICIO_TA", "DT_FIM_TA", "JUSTIFICATIVA_TA",
        ],
    },
    {
        "nome_tabela": "solicitacao_rendimento_aplicacao",
        "nome_csv": "siconv_solicitacao_rendimento_aplicacao.csv",
        "conflict_fields": ["id_solicitacao_rend_aplicacao"],
        "primary_key": ["id_solicitacao_rend_aplicacao"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_SOLICITACAO_REND_APLICACAO", "NR_CONVENIO", "NR_SOLICITACAO_REND_APLICACAO",
            "STATUS_SOLICITACAO_REND_APLICACAO", "DATA_SOLICITACAO_REND_APLICACAO",
            "VALOR_SOLICITACAO_REND_APLICACAO", "VALOR_APROVADO_SOLICITACAO_REND_APLICACAO",
        ],
    },
    {
        "nome_tabela": "prorroga_oficio",
        "nome_csv": "siconv_prorroga_oficio.csv",
        "conflict_fields": [],
        "primary_key": [],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "NR_PRORROGA", "DT_INICIO_PRORROGA", "DT_FIM_PRORROGA",
            "DIAS_PRORROGA", "DT_ASSINATURA_PRORROGA", "SIT_PRORROGA",
        ],
    },
    {
        "nome_tabela": "pagamento_tributo",
        "nome_csv": "siconv_pagamento_tributo.csv",
        "conflict_fields": ["nr_convenio", "data_tributo"],
        "primary_key": ["nr_convenio", "data_tributo"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "DATA_TRIBUTO", "VL_PAG_TRIBUTOS",
        ],
    },
    {
        "nome_tabela": "pagamento",
        "nome_csv": "siconv_pagamento.csv",
        "conflict_fields": ["nr_mov_fin"],
        "primary_key": ["nr_mov_fin"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "NR_MOV_FIN", "NR_CONVENIO", "IDENTIF_FORNECEDOR", "NOME_FORNECEDOR",
            "TP_MOV_FINANCEIRA", "DATA_PAG", "NR_DL", "DESC_DL",
            "VL_PAGO", "ID_DL", "DATA_EMISSAO_DL",
        ],
    },
    {
        "nome_tabela": "licitacao",
        "nome_csv": "siconv_licitacao.csv",
        "conflict_fields": ["id_licitacao"],
        "primary_key": ["id_licitacao"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_LICITACAO", "NR_CONVENIO", "NR_LICITACAO", "MODALIDADE_LICITACAO",
            "TP_PROCESSO_COMPRA", "TIPO_LICITACAO", "NR_PROCESSO_LICITACAO",
            "DATA_PUBLICACAO_LICITACAO", "DATA_ABERTURA_LICITACAO", "DATA_ENCERRAMENTO_LICITACAO",
            "DATA_HOMOLOGACAO_LICITACAO", "STATUS_LICITACAO", "SITUACAO_ACEITE_PROCESSO_EXECU",
            "SISTEMA_ORIGEM", "SITUACAO_SISTEMA", "VALOR_LICITACAO",
            "DATA_ANALISE_ACEITE", "DATA_ENVIO_ANALISE",
        ],
    },
    {
        "nome_tabela": "ingresso_contrapartida",
        "nome_csv": "siconv_ingresso_contrapartida.csv",
        "conflict_fields": ["nr_convenio", "dt_ingresso_contrapartida"],
        "primary_key": ["nr_convenio", "dt_ingresso_contrapartida"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "DT_INGRESSO_CONTRAPARTIDA", "VL_INGRESSO_CONTRAPARTIDA",
        ],
    },
    {
        "nome_tabela": "empenho",
        "nome_csv": "siconv_empenho.csv",
        "conflict_fields": [],
        "primary_key": [],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "ID_EMPENHO", "NR_CONVENIO", "NR_EMPENHO", "TIPO_NOTA", "DESC_TIPO_NOTA",
            "DATA_EMISSAO", "COD_SITUACAO_EMPENHO", "DESC_SITUACAO_EMPENHO",
            "UG_EMITENTE", "UG_RESPONSAVEL", "FONTE_RECURSO", "NATUREZA_DESPESA",
            "PLANO_INTERNO", "PTRES", "VALOR_EMPENHO", "RESULTADO_PRIMARIO",
            "OBSERVACAO_EMPENHO", "DESCRICAO_EMENDA_SIAFI",
        ],
    },
    {
        "nome_tabela": "historico_situacao",
        "nome_csv": "siconv_historico_situacao.csv",
        "conflict_fields": [],
        "primary_key": [],
        "truncate_before_insert": True,
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA", "NR_CONVENIO", "DIA_HISTORICO_SIT", "HISTORICO_SIT",
            "DIAS_HISTORICO_SIT", "COD_HISTORICO_SIT",
        ],
    },
    {
        "nome_tabela": "cronograma_desembolso",
        "nome_csv": "siconv_cronograma_desembolso.csv",
        "conflict_fields": ["id_proposta", "nr_convenio", "nr_parcela_crono_desembolso"],
        "primary_key": ["id_proposta", "nr_convenio", "nr_parcela_crono_desembolso"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA", "NR_CONVENIO", "NR_PARCELA_CRONO_DESEMBOLSO",
            "MES_CRONO_DESEMBOLSO", "ANO_CRONO_DESEMBOLSO", "TIPO_RESP_CRONO_DESEMBOLSO",
            "VALOR_PARCELA_CRONO_DESEMBOLSO",
        ],
    },
    {
        "nome_tabela": "meta_crono_fisico",
        "nome_csv": "siconv_meta_crono_fisico.csv",
        "conflict_fields": ["id_meta"],
        "primary_key": ["id_meta"],
        "truncate_before_insert": False,
        "skip_rows": 0,
        "colunas": [
            "ID_META", "ID_PROPOSTA", "NR_CONVENIO", "COD_PROGRAMA", "NOME_PROGRAMA",
            "NR_META", "TIPO_META", "DESC_META", "DATA_INICIO_META", "DATA_FIM_META",
            "UF_META", "MUNICIPIO_META", "ENDERECO_META", "CEP_META",
            "QTD_META", "UND_FORNECIMENTO_META", "VL_META",
        ],
    },
]