TABELAS_SICONV = [
    {
        "nome_tabela": "proposta",
        "nome_csv": "siconv_proposta.csv",
        "conflict_fields": ["id_proposta"],
        "primary_key": ["id_proposta"],
        "skip_rows": 0,
        "colunas": [
            "ID_PROPOSTA", "UF_PROPONENTE", "MUNIC_PROPONENTE", "COD_MUNIC_IBGE",
            "COD_ORGAO_SUP", "DESC_ORGAO_SUP", "NATUREZA_JURIDICA", "NR_PROPOSTA",
            "DIA_PROP", "MES_PROP", "ANO_PROP", "DIA_PROPOSTA", "COD_ORGAO",
            "DESC_ORGAO", "MODALIDADE", "IDENTIF_PROPONENTE", "NM_PROPONENTE",
            "CEP_PROPONENTE", "ENDERECO_PROPONENTE", "BAIRRO_PROPONENTE", "NM_BANCO",
            "NOME_SUBTIPO_PROPOSTA", "DESCRICAO_SUBTIPO_PROPOSTA", "VL_GLOBAL_PROP",
            "VL_REPASSE_PROP", "VL_CONTRAPARTIDA_PROP", "CD_AGENCIA", "CD_CONTA",
        ],
    },
    {
        "nome_tabela": "convenio",
        "nome_csv": "siconv_convenio.csv",
        "conflict_fields": ["nr_convenio"],
        "primary_key": ["nr_convenio"],
        "skip_rows": 0,
        "colunas": [
            "NR_CONVENIO", "ID_PROPOSTA", "DIA", "MES", "ANO", "DIA_ASSIN_CONV",
            "SIT_CONVENIO", "SUBSITUACAO_CONV", "SITUACAO_PUBLICACAO", "INSTRUMENTO_ATIVO",
            "IND_OPERA_OBTV", "NR_PROCESSO", "UG_EMITENTE", "DIA_PUBL_CONV",
            "DIA_INIC_VIGENC_CONV", "DIA_FIM_VIGENC_CONV", "DIA_FIM_VIGENC_ORIGINAL_CONV",
            "DIAS_PREST_CONTAS", "DIA_LIMITE_PREST_CONTAS", "DATA_SUSPENSIVA",
            "DATA_RETIRADA_SUSPENSIVA", "DIAS_CLAUSULA_SUSPENSIVA", "SITUACAO_CONTRATACAO",
            "IND_ASSINADO", "MOTIVO_SUSPENSAO", "IND_FOTO", "QTDE_CONVENIOS", "QTD_TA",
            "QTD_PRORROGA", "VL_GLOBAL_CONV", "VL_REPASSE_CONV", "VL_CONTRAPARTIDA_CONV",
            "VL_EMPENHADO_CONV", "VL_DESEMBOLSADO_CONV", "VL_SALDO_REMAN_TESOURO",
            "VL_SALDO_REMAN_CONVENENTE", "VL_RENDIMENTO_APLICACAO", "VL_INGRESSO_CONTRAPARTIDA",
            "VL_SALDO_CONTA", "VALOR_GLOBAL_ORIGINAL_CONV",
        ],
    },
]