{{ config(materialized="table") }}

with
    emendas as (
        select *
        from {{ ref("numero_transferencia") }}
    ),
    convenio as (
        select *
        from {{ ref("convenio") }}
    ),
    planos_acao as (
        select *
        from {{ ref("planos_acao_ted") }}
    )

select
    e.emissao_mes,
    e.emissao_dia,
    e.codigo_programa,
    e.programa,
    e.codigo_acao_ajustada,
    e.acao_ajustada,
    e.autor_emendas_orcamento_descricao,
    e.autor_emendas_orcamento_nome,
    e.uf,
    e.uf_descricao,
    e.municipio,
    e.pais,
    e.ne_ccor,
    e.ne_num_processo,
    e.ne_info_complementar,
    e.ne_ccor_descricao,
    e.doc_observacao,
    e.codigo_gnd,
    e.gnd,
    e.natureza_despesa,
    e.natureza_despesa_descricao,
    e.codigo_modalidade,
    e.modalidade,
    e.ne_ccor_favorecido,
    e.ne_ccor_favorecido_descricao,
    e.ne_ccor_ano_emissao,
    e.ptres,
    e.item_informacao,
    e.item_informacao_descricao,
    e.despesas_empenhadas,
    e.despesas_liquidadas,
    e.despesas_pagas,
    e.id_autor,
    e.cargo_autor,
    e.autor,
    e.partido,
    e.uf_autor,
    e.url_foto_autor,
    e.email_autor,
    e.url_foto_partido,
    e.numero_transferencia,
    e.dt_ingest,
    c.nr_convenio,
    c.id_proposta,
    c.dia,
    c.mes,
    c.ano,
    c.dia_assin_conv,
    c.sit_convenio,
    c.subsituacao_conv,
    c.situacao_publicacao,
    c.instrumento_ativo,
    c.ind_opera_obtv,
    c.nr_processo,
    c.ug_emitente,
    c.dia_publ_conv,
    c.dia_inic_vigenc_conv,
    c.dia_fim_vigenc_conv,
    c.dia_fim_vigenc_original_conv,
    c.dias_prest_contas,
    c.dia_limite_prest_contas,
    c.data_suspensiva,
    c.data_retirada_suspensiva,
    c.dias_clausula_suspensiva,
    c.situacao_contratacao,
    c.ind_assinado,
    c.motivo_suspensao,
    c.ind_foto,
    c.qtde_convenios,
    c.qtd_ta,
    c.qtd_prorroga,
    c.vl_global_conv,
    c.vl_repasse_conv,
    c.vl_contrapartida_conv,
    c.vl_empenhado_conv,
    c.vl_desembolsado_conv,
    c.vl_saldo_reman_tesouro,
    c.vl_saldo_reman_convenente,
    c.vl_rendimento_aplicacao,
    c.vl_ingresso_contrapartida,
    c.vl_saldo_conta,
    c.valor_global_original_conv,
    pa.id_plano_acao,
    pa.id_programa,
    pa.sigla_unidade_descentralizada,
    pa.unidade_descentralizada,
    pa.sigla_unidade_responsavel_execucao,
    pa.unidade_responsavel_execucao,
    pa.vl_total_plano_acao,
    pa.dt_inicio_vigencia,
    pa.dt_fim_vigencia,
    pa.tx_objeto_plano_acao,
    pa.tx_justificativa_plano_acao,
    pa.in_forma_execucao_direta,
    pa.in_forma_execucao_particulares,
    pa.in_forma_execucao_descentralizada,
    pa.tx_situacao_plano_acao,
    pa.aa_ano_plano_acao,
    pa.vl_beneficiario_especifico,
    pa.vl_chamamento_publico,
    pa.sq_instrumento,
    pa.aa_instrumento
from emendas e
left join convenio c on e.numero_transferencia = c.nr_convenio
left join planos_acao pa on e.numero_transferencia::text = pa.sq_instrumento