with
    educacao_principal as (
        select cpf, cod_escolaridade, nome_escolaridade, cod_titulacao, nome_titulacao
        from {{ ref("dados_escolares") }}
    ),
    uorg_completo as (
        select
            du.bairro_uorg,
            du.cep_uorg,
            du.codigo_matricula,
            du.codigo_municipio_uorg,
            du.codigo_orgao,
            du.codigo_orgao_uorg,
            du.email_uorg,
            du.tipo_endereco_uorg,
            du.logradouro_uorg,
            du.nome_municipio_uorg,
            du.nome_uorg,
            du.telefone_uorg,
            du.numero_endereco_uorg,
            du.sigla_uorg,
            du.uf_uorg,
            du.cpf,
            du.complemento_endereco_uorg,
            du.fax_uorg
        -- lu.dt_ultima_transacao AS dt_ultima_transacao_uorg, os codigos não batem e a
        -- informação aparentemente ja existe...
        -- lu.nome AS nome_uorg_lista
        from {{ ref("dados_uorg") }} du
    -- LEFT JOIN {{ ref('lista_uorgs') }} lu
    )
select
    dp.cpf,
    dp.nome_pessoa,
    dp.dt_nascimento,
    dp.grupo_sanguineo,
    dp.nome_cor,
    dp.cod_cor,
    dp.nome_estado_civil,
    dp.cod_estado_civil,
    dp.nome_mae,
    dp.nome_pai,
    dp.nome_municipio_nascimento,
    dp.nome_nacionalidade,
    dp.cod_nacionalidade,
    dp.nome_sexo,
    dp.cod_sexo,
    dp.num_pispasep,
    dp.uf_nascimento,
    dp.cod_deficiencia_fisica,
    dp.nome_deficiencia_fisica,
    dp.dt_chegada_brasil,
    dp.nome_pais_origem,

    df.cod_atividade_funcao,
    df.cod_funcao,
    df.cod_jornada,
    df.cod_ocorr_ingresso_orgao,
    df.cod_ocorr_ingresso_serv_publico,
    df.cod_orgao as cod_orgao_funcional,
    df.cod_padrao,
    df.cod_situacao_funcional,
    df.cod_uorg_exercicio,
    df.cod_upag,
    df.cod_orgao_origem,
    df.cpf_chefia_imediata,
    df.dt_exercicio_no_orgao,
    df.dt_fim_vale_ar,
    df.dt_ingresso_funcao,
    df.dt_ocorr_ingresso_orgao,
    df.dt_ocorr_ingresso_serv_publico,
    df.email_chefia_imediata,
    df.email_institucional,
    df.email_servidor,
    df.ident_unica as ident_unica_funcional,
    df.matricula_siape,
    df.modalidade_pgd,
    df.nome_atividade_funcao,
    df.nome_chefe_uorg,
    df.nome_funcao,
    df.nome_jornada,
    df.nome_ocorr_ingresso_orgao,
    df.nome_ocorr_ingresso_serv_publico,
    df.nome_orgao as nome_orgao_funcional,
    df.nome_regime_juridico,
    df.nome_situacao_funcional,
    df.nome_uorg_exercicio,
    df.nome_upag,
    df.participa_pgd,
    df.percentual_ts,
    df.sigla_orgao as sigla_orgao_funcional,
    df.sigla_orgao_origem,
    df.sigla_regime_juridico,
    df.sigla_uorg_exercicio,
    df.sigla_upag,
    df.cod_cargo,
    df.cod_classe,
    df.cod_ocorr_aposentadoria,
    df.dt_ini_vale_ar,
    df.dt_ocorr_aposentadoria,
    df.nome_cargo,
    df.nome_classe,
    df.nome_ocorr_aposentadoria,
    df.sigla_nivel_cargo,
    df.tipo_vale_ar,
    df.cod_ocorr_isencao_ir,
    df.dt_ini_ocorr_isencao_ir,
    df.nome_ocorr_isencao_ir,
    df.cod_uorg_lotacao,
    df.nome_uorg_lotacao,
    df.sigla_uorg_lotacao,
    df.dt_fim_ocorr_isencao_ir,
    df.cod_ocorr_exclusao,
    df.dt_ocorr_exclusao,
    df.nome_ocorr_exclusao,
    df.dt_uorg_lotacao,
    df.cod_vale_transporte,
    df.valor_vale_transporte,
    df.dt_uorg_exercicio,
    df.pontuacao_desempenho,

    ep.nome_escolaridade as nome_escolaridade_principal,
    ep.cod_escolaridade as cod_escolaridade_principal,
    ep.nome_titulacao as nome_titulacao_principal,
    ep.cod_titulacao as cod_titulacao_principal,

    ls.dt_ultima_transacao as dt_ultima_transacao_servidor,

    uorg_c.bairro_uorg,
    uorg_c.cep_uorg,
    uorg_c.codigo_matricula,
    uorg_c.codigo_municipio_uorg,
    uorg_c.codigo_orgao,
    uorg_c.codigo_orgao_uorg,
    uorg_c.email_uorg,
    uorg_c.tipo_endereco_uorg,
    uorg_c.logradouro_uorg,
    uorg_c.nome_municipio_uorg,
    uorg_c.nome_uorg,
    uorg_c.telefone_uorg,
    uorg_c.numero_endereco_uorg,
    uorg_c.sigla_uorg,
    uorg_c.uf_uorg,
    uorg_c.complemento_endereco_uorg,
    uorg_c.fax_uorg

from {{ ref("dados_pessoais") }} dp
left join {{ ref("dados_funcionais") }} df on dp.cpf = df.cpf
left join educacao_principal ep on dp.cpf = ep.cpf
left join {{ ref("lista_servidores") }} ls on dp.cpf = ls.cpf
left join uorg_completo uorg_c on dp.cpf = uorg_c.cpf
