{{ config(materialized='table')}}

with

    notas_credito_pre as (
        select
            nc,
            ptres,
            nc_transferencia,
            nc_ug_responsavel as ugr_codigo,
            nc_ug_responsavel_descricao as ugr_nome,
            nc_fonte_recursos as fonte_codigo,
            nc_fonte_recursos_descricao as fonte_nome,
            nc_plano_interno as pi_codigo,
            nc_plano_interno_descricao1 as pi_nome,
            favorecido_doc as favorecido_codigo,
            favorecido_doc_descricao as favorecido_nome,
            {{parse_financial_value("nc_valor_linha")}} as valor_celula, 
            (dt_ingest || '-03:00')::timestamptz as dt_ingest,
            programa_governo,
            programa_governo_descricao,
            acao_governo,
            acao_governo_descricao,
            nc_evento,
            nc_evento_descricao,
            nc_natureza_despesa,
            nc_natureza_despesa_descricao,
            nc_plano_interno_descricao2,
            favorecido_municipio,
            favorecido_municipio_descricao,
            {{parse_financial_value("movimento_liquido_moeda_origem")}} as movimento_liquido_moeda_origem,
            cast(null as date) as emissao_dia,
            cast(null as varchar) as emissao_mes,
            cast(null as varchar) as emissao_ano,
            cast(null as varchar) as dc,
            cast(null as varchar) as emitente_codigo,
            cast(null as varchar) as emitente_nome,
            cast(null as varchar) as gnd_codigo,
            cast(null as varchar) as gnd_nome,
            cast(null as varchar) as descricao,
            cast(null as varchar) as tipo_nc,
            cast(null as varchar) as nc_item_detalhamento,
            cast(null as varchar) as ro,
            00::numeric(15,2) as item_total,
            00::numeric(15,2) as total_lista,
            cast(null as varchar) as esfera_orcamentaria_codigo,
            cast(null as varchar) as esfera_orcamentaria_nome
        from {{ source("siafi", "nc_tesouro_pre_2026") }}
    ),
    notas_credito_pos as (
        select
            nc,
            ptres,
            nc_transferencia,
            ugr_codigo,
            ugr_nome,
            fonte_codigo,
            fonte_nome,
            pi_codigo,
            pi_nome,
            favorecido_codigo,
            favorecido_nome,
            {{parse_financial_value("valor_celula")}} as valor_celula,
            (dt_ingest || '-03:00')::timestamptz as dt_ingest,
            cast(null as varchar) as programa_governo,
            cast(null as varchar) as programa_governo_descricao,
            cast(null as varchar) as acao_governo,
            cast(null as varchar) as acao_governo_descricao,
            cast(null as varchar) as nc_evento,
            cast(null as varchar) as nc_evento_descricao,
            cast(null as varchar) as nc_natureza_despesa,
            cast(null as varchar) as nc_natureza_despesa_descricao,
            cast(null as varchar) as nc_plano_interno_descricao2,
            cast(null as varchar) as favorecido_municipio,
            cast(null as varchar) as favorecido_municipio_descricao,
            00::numeric(15,2) as movimento_liquido_moeda_origem,
            to_date(emissao_dia, 'DD/MM/YYYY') as emissao_dia,
            emissao_mes,
            emissao_ano,
            dc,
            emitente_codigo,
            emitente_nome,
            gnd_codigo,
            gnd_nome,
            descricao,
            tipo_nc,
            nc_item_detalhamento,
            ro,
            {{parse_financial_value("item_total")}} as item_total,
            {{parse_financial_value("total_lista")}} as total_lista,
            esfera_orcamentaria_codigo,
            esfera_orcamentaria_nome

        from {{ source("siafi", "nc_tesouro_pos__2026") }}
    )

select * from notas_credito_pre
union all
select * from notas_credito_pos